## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset=pd.read_excel("data for honesty predictor.xlsx")
X=dataset.iloc[:,1:-1].values # features with which we will predict the dependent variable predictors
y=dataset.iloc[:,-1].values # dependent variable



In [3]:
print(y)

[20400 25800 34000 40000 44200  7890  9680 13700 16000 17600  5630  7240
  9980 12400 13200  7440  9130 12900 15100 16600 13800 17000 24000 28100
 30900  5150  6730  9430 11300 12300  4010  5380  6990  8460  9250  5270
  6890  9640 11600 12600  2440  3260  4820  5880  6400  2670  3570  5280
  6440  7010  1900  2540  3750  4570  7980  6700  8950 13200 16100 17600]


In [4]:
print(X)

[['Data Scientist' 'UAE' 2]
 ['Data Scientist' 'UAE' 5]
 ['Data Scientist' 'UAE' 10]
 ['Data Scientist' 'UAE' 15]
 ['Data Scientist' 'UAE' 20]
 ['Data Scientist' 'US' 2]
 ['Data Scientist' 'US' 5]
 ['Data Scientist' 'US' 10]
 ['Data Scientist' 'US' 15]
 ['Data Scientist' 'US' 20]
 ['Data Scientist' 'UK' 2]
 ['Data Scientist' 'UK' 5]
 ['Data Scientist' 'UK' 10]
 ['Data Scientist' 'UK' 15]
 ['Data Scientist' 'UK' 20]
 ['Data Scientist' 'AUSTRALIA' 2]
 ['Data Scientist' 'AUSTRALIA' 5]
 ['Data Scientist' 'AUSTRALIA' 10]
 ['Data Scientist' 'AUSTRALIA' 15]
 ['Data Scientist' 'AUSTRALIA' 20]
 ['AI-ML Specialist' 'UAE' 2]
 ['AI-ML Specialist' 'UAE' 5]
 ['AI-ML Specialist' 'UAE' 10]
 ['AI-ML Specialist' 'UAE' 15]
 ['AI-ML Specialist' 'UAE' 20]
 ['AI-ML Specialist' 'US' 2]
 ['AI-ML Specialist' 'US' 5]
 ['AI-ML Specialist' 'US' 10]
 ['AI-ML Specialist' 'US' 15]
 ['AI-ML Specialist' 'US' 20]
 ['AI-ML Specialist' 'UK' 2]
 ['AI-ML Specialist' 'UK' 5]
 ['AI-ML Specialist' 'UK' 10]
 ['AI-ML Specialist

In [5]:
dataset.info() # getting the basic information regarding the dataset over here using this one

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Sno                60 non-null     int64 
 1   Occupation         60 non-null     object
 2   Location           60 non-null     object
 3   Experience         60 non-null     int64 
 4   Salary (CURRENCY)  60 non-null     int64 
dtypes: int64(3), object(2)
memory usage: 2.5+ KB


In [6]:
dataset.describe() # this will give the basic statistial information regarding the dataset

Sno  Experience  Salary (CURRENCY)
count  60.000000   60.000000          60.000000
mean   30.500000   10.400000       11812.500000
std    17.464249    6.585037        9049.618332
min     1.000000    2.000000        1900.000000
25%    15.750000    5.000000        5817.500000
50%    30.500000   10.000000        9190.000000
75%    45.250000   15.000000       14125.000000
max    60.000000   20.000000       44200.000000

## Encoding the dependent variables

In [7]:
from sklearn.preprocessing import OrdinalEncoder
column=dataset[["Location"]]
encoder = OrdinalEncoder()
X[:,1:2]= encoder.fit_transform(X[:,1:2])





In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X=np.array(ct.fit_transform(X))

In [9]:
print(X)

[[0.0 1.0 0.0 1.0 2]
 [0.0 1.0 0.0 1.0 5]
 [0.0 1.0 0.0 1.0 10]
 [0.0 1.0 0.0 1.0 15]
 [0.0 1.0 0.0 1.0 20]
 [0.0 1.0 0.0 3.0 2]
 [0.0 1.0 0.0 3.0 5]
 [0.0 1.0 0.0 3.0 10]
 [0.0 1.0 0.0 3.0 15]
 [0.0 1.0 0.0 3.0 20]
 [0.0 1.0 0.0 2.0 2]
 [0.0 1.0 0.0 2.0 5]
 [0.0 1.0 0.0 2.0 10]
 [0.0 1.0 0.0 2.0 15]
 [0.0 1.0 0.0 2.0 20]
 [0.0 1.0 0.0 0.0 2]
 [0.0 1.0 0.0 0.0 5]
 [0.0 1.0 0.0 0.0 10]
 [0.0 1.0 0.0 0.0 15]
 [0.0 1.0 0.0 0.0 20]
 [1.0 0.0 0.0 1.0 2]
 [1.0 0.0 0.0 1.0 5]
 [1.0 0.0 0.0 1.0 10]
 [1.0 0.0 0.0 1.0 15]
 [1.0 0.0 0.0 1.0 20]
 [1.0 0.0 0.0 3.0 2]
 [1.0 0.0 0.0 3.0 5]
 [1.0 0.0 0.0 3.0 10]
 [1.0 0.0 0.0 3.0 15]
 [1.0 0.0 0.0 3.0 20]
 [1.0 0.0 0.0 2.0 2]
 [1.0 0.0 0.0 2.0 5]
 [1.0 0.0 0.0 2.0 10]
 [1.0 0.0 0.0 2.0 15]
 [1.0 0.0 0.0 2.0 20]
 [1.0 0.0 0.0 0.0 2]
 [1.0 0.0 0.0 0.0 5]
 [1.0 0.0 0.0 0.0 10]
 [1.0 0.0 0.0 0.0 15]
 [1.0 0.0 0.0 0.0 20]
 [0.0 0.0 1.0 0.0 2]
 [0.0 0.0 1.0 0.0 5]
 [0.0 0.0 1.0 0.0 10]
 [0.0 0.0 1.0 0.0 15]
 [0.0 0.0 1.0 0.0 20]
 [0.0 0.0 1.0 3.0 2]
 [0.0 0

In [10]:
print(y)

[20400 25800 34000 40000 44200  7890  9680 13700 16000 17600  5630  7240
  9980 12400 13200  7440  9130 12900 15100 16600 13800 17000 24000 28100
 30900  5150  6730  9430 11300 12300  4010  5380  6990  8460  9250  5270
  6890  9640 11600 12600  2440  3260  4820  5880  6400  2670  3570  5280
  6440  7010  1900  2540  3750  4570  7980  6700  8950 13200 16100 17600]


## Spliiting the dataset into training set and testing set

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Training the model on the training set
POLYNOMIAL REGRESSION


In [12]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg=PolynomialFeatures(degree=4)
X_poly=poly_reg.fit_transform(X_train)
regressor=LinearRegression()
regressor.fit(X_poly,y_train)

LinearRegression()

## Predicting the results

In [13]:
y_pred = regressor.predict(poly_reg.fit_transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 6705.43  6730.  ]
 [ 5536.73  5270.  ]
 [24349.07 17600.  ]
 [11426.51 11300.  ]
 [ 5616.    7240.  ]
 [33260.17 34000.  ]
 [ 8193.36  9250.  ]
 [18934.29 16100.  ]
 [ 4339.81  2440.  ]
 [22775.36 24000.  ]
 [44726.45 44200.  ]
 [ 3076.03  5630.  ]]


In [14]:
print(X)

[[0.0 1.0 0.0 1.0 2]
 [0.0 1.0 0.0 1.0 5]
 [0.0 1.0 0.0 1.0 10]
 [0.0 1.0 0.0 1.0 15]
 [0.0 1.0 0.0 1.0 20]
 [0.0 1.0 0.0 3.0 2]
 [0.0 1.0 0.0 3.0 5]
 [0.0 1.0 0.0 3.0 10]
 [0.0 1.0 0.0 3.0 15]
 [0.0 1.0 0.0 3.0 20]
 [0.0 1.0 0.0 2.0 2]
 [0.0 1.0 0.0 2.0 5]
 [0.0 1.0 0.0 2.0 10]
 [0.0 1.0 0.0 2.0 15]
 [0.0 1.0 0.0 2.0 20]
 [0.0 1.0 0.0 0.0 2]
 [0.0 1.0 0.0 0.0 5]
 [0.0 1.0 0.0 0.0 10]
 [0.0 1.0 0.0 0.0 15]
 [0.0 1.0 0.0 0.0 20]
 [1.0 0.0 0.0 1.0 2]
 [1.0 0.0 0.0 1.0 5]
 [1.0 0.0 0.0 1.0 10]
 [1.0 0.0 0.0 1.0 15]
 [1.0 0.0 0.0 1.0 20]
 [1.0 0.0 0.0 3.0 2]
 [1.0 0.0 0.0 3.0 5]
 [1.0 0.0 0.0 3.0 10]
 [1.0 0.0 0.0 3.0 15]
 [1.0 0.0 0.0 3.0 20]
 [1.0 0.0 0.0 2.0 2]
 [1.0 0.0 0.0 2.0 5]
 [1.0 0.0 0.0 2.0 10]
 [1.0 0.0 0.0 2.0 15]
 [1.0 0.0 0.0 2.0 20]
 [1.0 0.0 0.0 0.0 2]
 [1.0 0.0 0.0 0.0 5]
 [1.0 0.0 0.0 0.0 10]
 [1.0 0.0 0.0 0.0 15]
 [1.0 0.0 0.0 0.0 20]
 [0.0 0.0 1.0 0.0 2]
 [0.0 0.0 1.0 0.0 5]
 [0.0 0.0 1.0 0.0 10]
 [0.0 0.0 1.0 0.0 15]
 [0.0 0.0 1.0 0.0 20]
 [0.0 0.0 1.0 3.0 2]
 [0.0 0

## Predicting the new results

### PREDICTING THE SALARY OF THE DATA SCIENTIST IN UAE WITH 0 WORK EXPERIENCE

In [17]:
print(regressor.predict(poly_reg.fit_transform([[0,1,0,1,2]])))

[20919.28]


## Evaluating the performance of machine learning model

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9615407833234401