## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset=pd.read_excel("data for honesty predictor.xlsx")
X=dataset.iloc[:,0:-1].values # features with which we will predict the dependent variable predictors
y=dataset.iloc[:,-1].values # dependent variable



In [3]:
dataset

Occupation    Location  Experience  Salary (In Rs)
0      Data Scientist         UAE           2          443850
1      Data Scientist          US           2          630560
2      Data Scientist          UK           2          540159
3      Data Scientist   AUSTRALIA           2          409624
4    AI-ML Specialist         UAE           2          300251
..                ...         ...         ...             ...
110    Data Scientist  Philippine          20          134307
111    Data Scientist   Argentina          20           61597
112    Data Scientist      Brazil          20          282158
113    Data Scientist       Egypt          20           81478
114    Data Scientist       Japan          20          655574

[115 rows x 4 columns]

In [4]:
print(y)

[ 443850  630560  540159  409624  300251  411582  384731  290150  134339
  213383  182291  145774   30500  193736   28464  174712  414987  290437
  201977  635354   51164  273832   35757   35757  119917   27045  773615
  694627  502670  369875  561340  541850  516173  379342  179485  285310
  243695  509402  373116  278092   68361   35792  154305   47282  357374
 1094890  957511  710235  522176  753636  670641  530749  265374 1094890
  957511  710235  522176  753636  670641   47826  213088   63325  500672
  739750  870294 1278704 1189693  831360  611382  903084  811677  638661
  323735  514678  438459  350293   64400  443854 1246034   55628  369714
  843148  638113  482558  123221   57068  263054   75568  603360  870294
  961675 1406574 1266447  913946  672302  983003  887472  693718  352364
  560232  765625  382929   69400  471646 1381741   61769  399020  926585
  693233  507432  134307   61597  282158   81478  655574]


In [5]:
print(X)

[['Data Scientist' 'UAE' 2]
 ['Data Scientist' 'US' 2]
 ['Data Scientist' 'UK' 2]
 ['Data Scientist' 'AUSTRALIA' 2]
 ['AI-ML Specialist' 'UAE' 2]
 ['AI-ML Specialist' 'US' 2]
 ['AI-ML Specialist' 'UK' 2]
 ['AI-ML Specialist' 'AUSTRALIA' 2]
 ['Graphic Designer' 'AUSTRALIA' 2]
 ['Graphic Designer' 'US' 2]
 ['Graphic Designer' 'UK' 2]
 ['Graphic Designer' 'UAE' 2]
 ['Data Scientist' 'India' 2]
 ['Data Scientist' 'Spain' 2]
 ['Data Scientist' 'Pakistan' 2]
 ['Data Scientist' 'Jordan' 2]
 ['Data Scientist' 'denmark' 2]
 ['Data Scientist' 'bahrain' 2]
 ['Data Scientist' 'new zealand' 2]
 ['Data Scientist' 'Canada' 2]
 ['Data Scientist' 'Philippine' 2]
 ['Data Scientist' 'Japan' 2]
 ['Data Scientist' 'Egypt' 2]
 ['Data Scientist' 'Egypt' 2]
 ['Data Scientist' 'Brazil' 2]
 ['Data Scientist' 'Argentina' 2]
 ['Data Scientist' 'US' 5]
 ['Data Scientist' 'UK' 5]
 ['Data Scientist' 'AUSTRALIA' 5]
 ['AI-ML Specialist' 'UAE' 5]
 ['Data Scientist' 'UAE' 5]
 ['AI-ML Specialist' 'US' 5]
 ['AI-ML Special

In [6]:
dataset.info() # getting the basic information regarding the dataset over here using this one

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Occupation      115 non-null    object
 1   Location        115 non-null    object
 2   Experience      115 non-null    int64 
 3   Salary (In Rs)  115 non-null    int64 
dtypes: int64(2), object(2)
memory usage: 3.7+ KB


In [7]:
dataset.describe() # this will give the basic statistial information regarding the dataset

Experience  Salary (In Rs)
count  115.000000    1.150000e+02
mean    10.669565    4.845327e+05
std      6.778089    3.426628e+05
min      2.000000    2.704500e+04
25%      5.000000    1.978565e+05
50%     10.000000    4.438500e+05
75%     15.000000    6.941725e+05
max     20.000000    1.406574e+06

## Encoding the dependent variables

In [8]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
X[:,1:2]=encoder.fit_transform(X[:,1:2])


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X=np.array(ct.fit_transform(X))


In [9]:
print(X)

[[0.0 1.0 0.0 11.0 2]
 [0.0 1.0 0.0 13.0 2]
 [0.0 1.0 0.0 12.0 2]
 [0.0 1.0 0.0 0.0 2]
 [1.0 0.0 0.0 11.0 2]
 [1.0 0.0 0.0 13.0 2]
 [1.0 0.0 0.0 12.0 2]
 [1.0 0.0 0.0 0.0 2]
 [0.0 0.0 1.0 0.0 2]
 [0.0 0.0 1.0 13.0 2]
 [0.0 0.0 1.0 12.0 2]
 [0.0 0.0 1.0 11.0 2]
 [0.0 1.0 0.0 5.0 2]
 [0.0 1.0 0.0 10.0 2]
 [0.0 1.0 0.0 8.0 2]
 [0.0 1.0 0.0 7.0 2]
 [0.0 1.0 0.0 15.0 2]
 [0.0 1.0 0.0 14.0 2]
 [0.0 1.0 0.0 16.0 2]
 [0.0 1.0 0.0 3.0 2]
 [0.0 1.0 0.0 9.0 2]
 [0.0 1.0 0.0 6.0 2]
 [0.0 1.0 0.0 4.0 2]
 [0.0 1.0 0.0 4.0 2]
 [0.0 1.0 0.0 2.0 2]
 [0.0 1.0 0.0 1.0 2]
 [0.0 1.0 0.0 13.0 5]
 [0.0 1.0 0.0 12.0 5]
 [0.0 1.0 0.0 0.0 5]
 [1.0 0.0 0.0 11.0 5]
 [0.0 1.0 0.0 11.0 5]
 [1.0 0.0 0.0 13.0 5]
 [1.0 0.0 0.0 12.0 5]
 [1.0 0.0 0.0 0.0 5]
 [0.0 0.0 1.0 0.0 5]
 [0.0 0.0 1.0 13.0 5]
 [0.0 0.0 1.0 12.0 5]
 [0.0 1.0 0.0 15.0 5]
 [0.0 1.0 0.0 14.0 5]
 [0.0 1.0 0.0 16.0 5]
 [0.0 1.0 0.0 9.0 5]
 [0.0 1.0 0.0 1.0 5]
 [0.0 1.0 0.0 2.0 5]
 [0.0 1.0 0.0 4.0 5]
 [0.0 1.0 0.0 6.0 5]
 [0.0 1.0 0.0 13.0 10]
 [0.0 1.

## Spliiting the dataset into training set and testing set

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [11]:

# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# y_train=sc.fit_transform(y_train)

## Training the model on the training set
POLYNOMIAL REGRESSION


In [27]:
# from sklearn.preprocessing import PolynomialFeatures
# from sklearn.linear_model import LinearRegression
# poly_reg=PolynomialFeatures(degree=4)
# X_poly=poly_reg.fit_transform(X_train)
# regressor=LinearRegression()
# regressor.fit(X_poly,y_train)

# from sklearn.tree import DecisionTreeRegressor
# regressor=DecisionTreeRegressor(random_state=0)
# regressor.fit(X_train,y_train)

from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=25,random_state=0)
regressor.fit(X_train,y_train)

# from sklearn.linear_model import LinearRegression
# regressor=LinearRegression()
# regressor.fit(X_train,y_train)



RandomForestRegressor(n_estimators=25, random_state=0)

## Predicting the results

In [28]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 237659.36  182291.  ]
 [ 657441.44  438459.  ]
 [1134437.4  1189693.  ]
 [ 577966.04  530749.  ]
 [ 404492.24  290150.  ]
 [ 949922.36 1246034.  ]
 [1271840.08 1406574.  ]
 [ 772642.68  870294.  ]
 [ 357270.72  399020.  ]
 [ 391583.48  500672.  ]
 [ 470060.24  561340.  ]
 [ 510576.6   540159.  ]
 [ 772779.48  913946.  ]
 [ 111557.84   35757.  ]
 [ 112138.12   47282.  ]
 [ 730765.96  926585.  ]
 [ 246440.6   119917.  ]
 [ 610167.88  514678.  ]
 [ 199888.12  213088.  ]
 [ 519672.92  522176.  ]
 [ 355287.72  414987.  ]
 [ 257395.76  193736.  ]
 [ 540224.2   773615.  ]]


## Predicting the new results

### PREDICTING THE SALARY OF THE DATA SCIENTIST IN UAE WITH 0 WORK EXPERIENCE

In [30]:
print(regressor.predict([[0,1,0,11,0]]))

[455431.44]


## Evaluating the performance of machine learning model

In [31]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8884690710306652